name: Continuous Deployment (Prod)

on:
  push: 
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}        
          password: ${{ secrets.DOCKER_SECRET }}        

      - name: Set up Docker Buildx
        uses: docker/build-push-action@v2

      - name: Build and Push Image
        uses: docker/build-push-action@v4  
        with:
          context: .
          file: Dockerfile
          push: true
          tags: 10mindesign/argocd:${{ github.sha }}

      # - name: Clone manifest repo, update image to letest sha and push    
      #   env:
      #     PAT: ${{ secrets.PAT }}
      #   run: |
      #     git clone https://github.com/10MinDesign-Invite/k8s.git  
      #     cd k8s

      #     sed -i 's|image:argocd/test:.*|image: argocd/test:${{ github.sha }}|' argocd/prod.yml 

      #     git config user.name "Github Actions Bot"
      #     git config user.email "actions@github.com"
      #     git add .
      #     git commit -m "update image tag to latest ${{ github.sha }}"
      #     git push https://${{PAT}}github.com/10MinDesign-Invite/k8s.git main